Update apiAutomation-0x00

diff --git a/Advanced_shell/apiAutomation-0x00 b/Advanced_shell/apiAutomation-0x00
--- a/Advanced_shell/apiAutomation-0x00
+++ b/Advanced_shell/apiAutomation-0x00
@@ -1,8 +1,8 @@
 #!/bin/bash
 SCRIPT_PATH="$0"
 if [ ! -s "$SCRIPT_PATH" ]; then 
-echo "Error: Script file '$SCRIPT_PATH' does not or is empty."
-exit 1
+  echo "Error: Script file '$SCRIPT_PATH' does not or is empty."
+  exit 1
 fi
 
 URL="https://pokeapi.co/api/v2/pokemon/pikachu"
@@ -12,6 +12,6 @@ ERROR_FILE="errors.txt"
 HTTP_STATUS=$(curl -s -w "%{http_code}" "$URL" -o "$OUTPUT_FILE")
 
 if [ "HTTP_STATUS" -ne 200 ]; then
-echo "$(date) - Failed with status code $HTTP_TATUS" >> "$ERROR_FILE"
-rm -f "$OUTPUT_FILE"
+  echo "$(date) - Failed with status code $HTTP_TATUS" >> "$ERROR_FILE"
+  rm -f "$OUTPUT_FILE"
 fi
