Update data_extraction_automation-0x01

diff --git a/Advanced_shell/data_extraction_automation-0x01 b/Advanced_shell/data_extraction_automation-0x01
--- a/Advanced_shell/data_extraction_automation-0x01
+++ b/Advanced_shell/data_extraction_automation-0x01
@@ -1,13 +1,13 @@
 #!/bin/bash
 
 if [! -s "$0"]; then
-echo "Error: Script is empty or missing."
-exit 1
+  echo "Error: Script is empty or missing."
+  exit 1
 fi
 
 if [! -f data.json]; then
-echo "Error: data.json not found."
-exit 1
+  echo "Error: data.json not found."
+  exit 1
 fi
 
 name=$(jq -r '.name' data.json | sed 's/.*/\u&/')
